/**
 * Created by Administrator on 2016/8/16.
 */
var myapp=angular.module("myapp",[]);
myapp.run(["$rootScope","$location",function($rootScope,$location){
    $rootScope.$on("$routeChangeSuccess",function(event,c,p){
    })
}])
//路由配置
myapp.config(['$routeProvider', function($routeProvider){
    $routeProvider
        .when('/home',{
            controller:"homeCtrl",
            templateUrl:'view/home.html'})
        .when('/register',{
            templateUrl:'view/register.html'})
        .when('/testview',{
            templateUrl:'view/testview.html'})
        .when('/findpwback',{
            templateUrl:'view/findpwback.html'})
        .when('/mymcard',{
            templateUrl:'view/mymcard.html'})
        .when('/mysinpage',{
            templateUrl:'view/mysinpage.html'})
        .when('/productlib',{
            templateUrl:'view/productlib.html'})
        .when('/cardholder',{
            templateUrl:'view/cardholder.html'})
        .when('/joinmember',{
            templateUrl:'view/joinmember.html'})
        .when('/newsinpage',{
            templateUrl:'view/newsinpage.html'})
        .when('/setting',{
            templateUrl:'view/setting.html'})
        .when('/accountmanage',{
            templateUrl:'view/accountmanage.html'})
        .when('/changetel',{
            templateUrl:'view/changetel.html'})
        .when('/vipmember',{
            templateUrl:'view/vipmember.html'})
        .when('/enpmanage',{
            templateUrl:'view/enpmanage.html'})
        .when('/enpcard',{
            templateUrl:'view/enpcard.html'})
        .when('/enpcardholder',{
                templateUrl:'view/enpcardholder.html'})
        .when('/admsetting',{
            templateUrl:'view/admsetting.html'})
        .when('/departsetting',{
            templateUrl:'view/departsetting.html'})
        .when('/membership',{
                templateUrl:'view/membership.html'})
        .when('/persetting',{
            templateUrl:'view/persetting.html'})
        .when('/systeminfo',{
                templateUrl:'view/systeminfo.html'})
         .when('/mcardedit',{
                templateUrl:'view/mcardedit.html'})
          .when('/historyrecord',{
                templateUrl:'view/historyrecord.html'})
          .when('/uploadgoods',{
                templateUrl:'view/uploadgoods.html'})
        .otherwise({
            redirectTo:'/home'});
}])


